### ISSUE TITLE
Background Image issue 

### ISSUE THREAD

**Issue by abhisheksahu2001** [Motschen/Retroblur#2]
when i try to change  background image from local source it does not change 
I did spicetify update  ,shift+ctrl+R  after changing bg in css
help

**Comment by Motschen** [comment]
You could try using `spicetify apply` after changing it.

**Comment by abhisheksahu2001** [comment]
still not working

**Comment by Motschen** [comment]
What exactly do you mean by "local source"?
That sounds like you're trying to use a picture that's saved on your hard disk.
Due to Spicetify/CSS limitations however, only pictures from online sources are supported.
I recommend you to upload your images to [Imgur](https://imgur.com/) or [PictShare](https://pictshare.net/).
